name: action
on: [push, pull_request]
  
jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/setup-python@v1
      - uses: actions/checkout@v2
      - name: Run
        shell: bash
        run: |
          docker buildx build --platform linux/amd64 -t test .
